Fix:ecommerce lookml
fishtown-analytics/ecommerce pull request #23
Opened 2019-01-29 21:01 UTC by axelazaid

* update `.lkml` files to include measures and dimensions in the ecommerce package
  -  added descriptions to dimensions and measures

2019-01-29 21:02 UTC, jthandy commented
@axelazaid I actually have essentially no background with this package so I'll let @eogilvy12 do the review here!

2019-01-30 15:34 UTC, eogilvy12 commented on lookml/customers.view.lkml
> +  dimension_group: created_date {
I think you should have this field be `created` to keep consistent with removing `date` from your timestamps

2019-01-30 15:35 UTC, eogilvy12 commented on lookml/customers.view.lkml
> +  dimension: first_name {
remove first name, last name and phone

2019-01-30 15:37 UTC, eogilvy12 commented on lookml/ecommerce.model.lkml
> +  label: "Shopify Customers"
remove label. this is for the ecom package and will not always be shopify data!

2019-01-30 15:37 UTC, eogilvy12 commented on lookml/ecommerce.model.lkml
> +  label: "Shopify Orders"
remove shopify

2019-01-30 15:39 UTC, eogilvy12 commented on lookml/order_items.view.lkml
> +    type: string
i think this should be a number

2019-01-30 15:39 UTC, eogilvy12 commented on lookml/order_items.view.lkml
> +    type: string
i think this should also be a number normally.

2019-01-30 15:39 UTC, eogilvy12 commented on lookml/order_items.view.lkml
> +  dimension: product_sku {
this is more frequently called sku not product_sku

2019-01-30 15:42 UTC, eogilvy12 commented on lookml/orders.view.lkml
> +    type: string
i think this is normally a number as well

2019-01-30 15:42 UTC, eogilvy12 commented on lookml/orders.view.lkml
> +  dimension_group: created_at {
i think we may want to rename this created

2019-01-30 15:44 UTC, eogilvy12 commented on lookml/orders.view.lkml
> +    description: "This returns '1' if order is completed (financial_status in ('paid', 'partially_paid', 'partially_refunded')), '0' if no"
update this description- this is very specific to shopify. it should say this returns 1 if the parameters for a completed order have been fulfilled

2019-01-30 15:44 UTC, eogilvy12 commented on lookml/orders.view.lkml
> +  dimension: order_number {
I think this is a shopify field. please check on this. order_seq_number is hidden above but it is what we create as the order number

2019-01-30 15:45 UTC, eogilvy12 commented on lookml/orders.view.lkml
> +  dimension: billing_address_id {
I think you should remove billing shipping and location id - these are shopify specific

2019-01-30 15:46 UTC, eogilvy12 commented on lookml/products.view.lkml
I don't think we need a measure on this table

2019-01-30 15:47 UTC, eogilvy12 commented on lookml/products.view.lkml
> +  dimension: vendor {
vendor is specific to shopify

2019-01-30 15:48 UTC, eogilvy12 requested changes
@alexa I put comments within each file. let me know if you have questions!

once we have this updated, we need to update the dashboard lookml file and test that these changes are maintained before merging in

2019-01-30 21:44 UTC, eogilvy12 approved these changes
this looks excellent! now we can move onto the dashboard lookml updating. I think we should include that in this PR so do not merge this in yet - let's chat about how to best tackle the next step.

2019-02-04 14:31 UTC, eogilvy12 requested changes
Can you schedule 15 minutes to review the output of this with me? @axelazaid I think we should add a few reports to the main dashboard

2020-07-31 16:54 UTC, clrcrl commented
Closing due to deprecation

2020-07-31 16:54 UTC, closed without merging